name: Cargo Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build and test
        run: cargo build --release && cargo test

      - name: Create release
        run: cargo release --skip-publish --skip-push

      - name: Publish release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo release --execute